### ISSUE TITLE
Add link to account settings from other pages

### ISSUE THREAD

**Issue by FortyFourForks** [AviUB/CSE442-Project#54]
***Task Test***
Test 1
1) Navigate to mealoclock.herokuapp.com
2) login with username: test_user password: testPassword
3) click the Account Settings link
4) confirm /profile loads

Test 2
1) Navigate to mealoclock.herokuapp.com
2) login with username: test_user password: testPassword
3) click link to the calendar page
4) Click the Account Settings link
5) confirm /profile loads

Test 3
1) Navigate to mealoclock.herokuapp.com
2) login with username: test_user password: testPassword
3) click link to the About Us page
4) Click the Account Settings link
5) confirm /profile loads

**Comment by alejandrorizquierdo** [comment]
![Screen Shot 2021-11-09 at 2.03.55 PM.png](https://images.zenhubusercontent.com/601af44da23730ce3f2d62d8/f88eb907-6ee7-441a-9701-ce55ca527bf1)

**Comment by alejandrorizquierdo** [comment]
https://images.zenhubusercontent.com/404770692/c091cc08-93a8-4757-a583-aaa5033a0aeb/mealoclock.mov
